version: '3.7'

services:

    postgres:
        image: postgres
        container_name: postgres-gobarber
        environment:
            POSTGRES_PASSWORD: docker
        restart: always
        ports:
            - "5432:5432"
    mongo:
        image: mongo
        container_name: mongo-gobarber
        restart: always
        ports:
            - "27017:27017"
    redis:
        image: redis:alpine
        container_name: redis-gobarberdocker
        restart: always
        ports:
            - "6379:6379"
